select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_Control_Mode
    name: "${device_type}-Battery Control Mode"
    address: 98
    value_type: U_WORD
    optionsmap:
      "Lead Acid": 0
      "Lithium (BMS)": 1

  # To be completed
  #- platform: modbus_controller
  #  use_write_multiple: true
  #  modbus_controller_id: ${modbus_controller_id}
  #  id: ${device_type}_Battery_Lithium_Type
  #  name: "${device_type}-Battery Lithium Type"
  #  address: 223
  #  bitmask: 0x1
  #  value_type: U_WORD
  #  optionsmap:
  #    "Pylon (CAN)": 0
  #    "": 1

number:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_Equalization_voltage
    name: "${device_type}-Battery Equalization voltage"
    address: 99
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 100.0
    min_value: 38.00
    max_value: 61.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_Absorption_voltage
    name: "${device_type}-Battery Absorption voltage"
    address: 100
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 100.0
    min_value: 38.00
    max_value: 61.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_Float_voltage
    name: "${device_type}-Battery Float voltage"
    address: 101
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 100.0
    min_value: 38.00
    max_value: 61.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_Equalization_day_cycle
    name: "${device_type}-Battery Equalization Day Cycle"
    address: 105
    unit_of_measurement: days
    value_type: U_WORD
    multiply: 1.0
    min_value: 0.0
    max_value: 90.0

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_Equalization_Time
    name: "${device_type}-Battery Equalization Time"
    address: 106
    unit_of_measurement: days
    value_type: U_WORD
    multiply: 1.0
    step: 0.5
    min_value: 0.0
    max_value: 20.0

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Battery_capacity
    name: "${device_type}-Battery capacity"
    address: 101
    unit_of_measurement: V
    value_type: U_WORD
    multiply: 1.0
    min_value: 0.00
    max_value: 2000.00

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Maximum_battery_charge_current
    name: "${device_type}-Maximum battery charge current"
    address: 108
    unit_of_measurement: A
    value_type: U_WORD

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    id: ${device_type}_Maximum_battery_discharge_current
    name: "${device_type}-Maximum battery discharge current"
    address: 109
    unit_of_measurement: A
    value_type: U_WORD




sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 5
    name: "${device_type}-Total charge of the battery"
    id:  ${device_type}_battery_total_charge
    register_type: holding
    address: 516
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 5
    name: "${device_type}-Total discharge of the battery"
    id:  ${device_type}_battery_total_discharge
    register_type: holding
    address: 518
    unit_of_measurement: "kWh"
    state_class: "total_increasing"
    device_class: energy
    accuracy_decimals: 1
    value_type: U_DWORD_R
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-battery temperature"
    id:  ${device_type}_battery_temperature
    register_type: holding
    address: 586
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    value_type: U_WORD
    filters:
      - offset: -1000
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-battery voltage"
    id: ${device_type}_battery_voltage
    register_type: holding
    address: 587
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${device_type}-battery capacity"
    id: ${device_type}_battery_capacity
    register_type: holding
    address: 588
    unit_of_measurement: "%"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Battery output power"
    id: ${device_type}_Battery_output_power
    register_type: holding
    address: 590
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 0
    value_type: S_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Battery output current"
    id: ${device_type}_Battery_output_current
    register_type: holding
    address: 591
    unit_of_measurement: "A"
    state_class: "measurement"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
    value_type: S_WORD