binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${device_type}-AC INV Relay" # bit 0
    id: "${entities_id_prefix}_AC_INV_Relay"
    register_type: holding
    address: 552
    bitmask: 0x1

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${device_type}-General - AC Load Relay Reserved" # bit 1
    id: "${entities_id_prefix}_General_AC_Load_Relay_Reserved"
    register_type: holding
    address: 552
    bitmask: 0x2

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${device_type}-General - AC Grid Relay" # bit 2
    id: "${entities_id_prefix}_General_AC_Grid_Relay"
    register_type: holding
    address: 552
    bitmask: 0x4

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${device_type}-General - AC Generator Relay" # bit 3
    id: "${entities_id_prefix}_General_AC_Generator_Relay"
    register_type: holding
    address: 552
    bitmask: 0x8

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    skip_updates: 2
    name: "${device_type}-General - Turn off/on status"
    id: "${entities_id_prefix}_General_Turn_off_on_status"
    register_type: holding
    address: 551
    bitmask: 0x1

sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-General - Heatsink Temperature"
    id: "${entities_id_prefix}_General_Heatsink_Temperature"
    register_type: holding
    address: 541
    unit_of_measurement: "°C"
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - offset: -1000
      - multiply:  0.1

select:
  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-General - Energy Priority"
    id: "${entities_id_prefix}_General_Energy_Priority"
    address: 141
    value_type: U_WORD
    optionsmap:
      "Battery first": 0
      "Load first": 1

  - platform: modbus_controller
    use_write_multiple: true
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-General - Limit Control Mode"
    id: "${entities_id_prefix}_Limit_Control_Mode"
    address: 142
    value_type: U_WORD
    optionsmap:
      "Selling first": 0
      "Zero export to load": 1
      "Zero export to CT": 2
