sensor:
  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Phase Voltage L1"
    id: ${device_type}_Generator_Phase_Voltage_L1
    register_type: holding
    address: 661
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filter:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Phase Voltage L2"
    id: ${device_type}_Generator_Phase_Voltage_L1
    register_type: holding
    address: 662
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filter:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Phase Voltage L3"
    id: ${device_type}_Generator_Phase_Voltage_L1
    register_type: holding
    address: 663
    unit_of_measurement: "V"
    state_class: "measurement"
    accuracy_decimals: 1
    filter:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Phase Power L1"
    id: ${device_type}_Generator_Phase_Power_L1
    register_type: holding
    address: 664
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    filter:
      - multiply: 0.1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Phase Power L2"
    id: ${device_type}_Generator_Phase_Power_L1
    register_type: holding
    address: 665
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Phase Power L3"
    id: ${device_type}_Generator_Phase_Power_L1
    register_type: holding
    address: 666
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD

  - platform: modbus_controller
    modbus_controller_id: ${modbus_controller_id}
    name: "${device_type}-Generator Total Power"
    id: ${device_type}_Generator_Total_Power
    register_type: holding
    address: 667
    unit_of_measurement: "W"
    state_class: "measurement"
    accuracy_decimals: 1
    value_type: U_WORD