substitutions:
  name: !secret host_name                                            # Name in ESPhome
  device_description: "Esphome component for Deye sun-12k-sg04lp3"   # Description in ESPhome
  modbus_controller_id: sg04lp3                                      # Just a random name for the modbus controler
  device_type: sun12k                                                # All entities in Home Assistant will start with this text to help identify the entitys 

packages:
  api: !include config/api.yaml
  mqtt: !include
    file: config/mqtt.yaml
    vars:
      mqtt_discovery: false # If "api" is included, turn off autodiscovery feature for Home Assistant
      #mqtt_discovery: true # If "api" is NOT included, turn on MQTT autodiscovery feature for Home Assistant
  wifi: !include config/wifi.yaml
  ota: !include config/ota.yaml
  web_server: !include config/web_server.yaml
  esphome: !include config/esphome.yaml
  board: !include config/esp32.yaml
  logger: !include config/logging.yaml
  captive_portal: !include config/captive_portal.yaml
  modbus: !include config/modbus.yaml
  #
  # Different modules for the different sections of the inverter
  solar: !include modules/solar.yaml
  battery: !include modules/battery.yaml
  #
  load: !include modules/load.yaml
  generator: !include modules/generator.yaml # Generator, Micro Inverter or Smart Load
  general: !include modules/general.yaml
  status: !include modules/status.yaml
  internal: !include modules/internal.yaml # Internal CTs Current/Power Measurement
  inverter: !include modules/inverter.yaml
  ups: !include modules/ups.yaml
  out-of-grid: !include modules/out-of-grid.yaml

  # Time of Use for Grid-Connected Systems
  time-of-use-common: !include modules/time-of-use-common.yaml

  # Only Include ONE of these (select OR number)
  time-of-use-time-as-select: !include modules/time-of-use-time-as-select.yaml
  #time-of-use-time-as-number: !include modules/time-of-use-time-as-number.yaml

  #
  # Enable for grid-connected systems
  #grid: !include modules/grid.yaml
  #external: !include modules/external.yaml # External CTs Current/Power Measurement
